In [1]:
import pandas as pd

In [2]:
def insert(df, inserting):
    if len(inserting) > len(df.columns):
        while len(inserting) > len(df.columns):
            new_column = ['' for i in range(len(df))]
            df.insert(len(df.columns), f'Character {len(df.columns) + 1}', new_column, True)
    elif len(inserting) < len(df.columns):
        while len(inserting) < len(df.columns):
            inserting.append('')
    
    if len(df) == 1 and df.loc['Page 1'][0] == '':
        df.loc['Page 1'] = inserting
    else:
        df.loc[f'Page {len(df) + 1}'] = inserting
    
    return df

In [3]:
df = pd.DataFrame({'Page': ['Page 1']})
df.set_index('Page', inplace = True)

inserting = ['Cebolinha']
df = insert(df, inserting)
inserting = ['Mônica', 'Magali']
df = insert(df, inserting)
inserting = ['Xaveco', 'Cascão', 'Titi', 'Humberto']
df = insert(df, inserting)
inserting = ['Cascuda', 'Cascão']
df = insert(df, inserting)
inserting = []
df = insert(df, inserting)
inserting = ['Cascuda', 'Cascão']
df = insert(df, inserting)

df

       Character 1 Character 2 Character 3 Character 4
Page
Page 1   Cebolinha
Page 2      Mônica      Magali
Page 3      Xaveco      Cascão        Titi    Humberto
Page 4     Cascuda      Cascão
Page 5
Page 6     Cascuda      Cascão